spring.application.name=producer-service
# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Custom Topic Property
topic.name=gi-topic1

server.port=8081

spring.kafka.producer.properties.spring.json.add.type.headers=false